In [4]:
import numpy as np
import pandas as pd

In [11]:
IC50_AUC_SMILES = pd.read_csv("./data/IC50_AUC_SMILES_final_train.csv")
IC50_AUC_SMILES

,CellLineID,smiles,AUC,IC50
0,ACH-000001,CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=C4C3...,0.967187,NaN
1,ACH-000001,CCC1(CC2CC(C3=C(CCN(C2)C1)C4=CC=CC=C4N3)(C5=C(...,0.666062,NaN
2,ACH-000001,N.N.[Cl-].[Cl-].[Pt+2],0.977907,NaN
3,ACH-000001,CC1=C2C(C(=O)C3(C(CC4C(C3C(C(C2(C)C)(CC1OC(=O)...,0.922989,NaN
4,ACH-000001,COC1=C(C=C2C(=C1)N=CN=C2NC3=CC(=C(C=C3)F)Cl)OC...,0.957586,NaN
...,...,...,...,...
95259,ACH-002317,CC1=CN=C(N=C1C2=CNC(=C2)C(=O)NC(CO)C3=CC(=CC=C...,0.946713,NaN
95260,ACH-002317,C1COCCN1C2=CC=C(C=C2)C3=C(C=NC=C3)C4=CC(=C(C(=...,0.926422,NaN
95261,ACH-002317,CC1CN(CC(N1)C)C2=NC=C(C(=C2)C)C3=CC=C(C=C3)C4=...,0.916274,3.25832
95262,ACH-002317,C1CC(C1)NC2=NC=CC(=C2)C(=O)NCC(CN3CCC4=CC=CC=C...,0.906540,NaN
95263,ACH-002317,C1=CC(=CC=C1C2=CNN=C2)C(CN)(C3=CC=C(C=C3)Cl)O,0.996681,NaN

In [10]:
metabolomics = pd.read_csv("./data/Metabolomics_subsetted.csv")
metabolomics = metabolomics.rename(columns={metabolomics.columns[0]: "CellLineID"})
metabolomics

,CellLineID,2-aminoadipate,3-phosphoglycerate,alpha-glycerophosphate,4-pyridoxate,aconitate,adenine,adipate,alpha-ketoglutarate,AMP,...,C56:8 TAG,C56:7 TAG,C56:6 TAG,C56:5 TAG,C56:4 TAG,C56:3 TAG,C56:2 TAG,C58:8 TAG,C58:7 TAG,C58:6 TAG
0,ACH-000698,6.112727,6.034198,5.896896,6.000532,5.513618,5.868529,5.977177,5.693074,5.923737,...,6.070239,6.133433,6.091089,6.257711,6.372732,6.202511,5.939576,6.309821,6.115974,5.999436
1,ACH-000489,5.577413,5.727045,5.111468,6.073250,5.802494,5.824473,5.888821,5.768379,5.760784,...,6.248653,6.633575,6.378052,6.341043,6.360945,6.333540,6.137271,7.065858,6.832174,6.363064
2,ACH-000431,5.886398,5.574881,5.541259,5.848375,5.665026,5.875548,5.894904,5.839640,5.742613,...,5.942887,5.946988,5.837980,5.913350,6.137530,5.807546,5.704149,5.881193,5.785208,5.504225
3,ACH-000707,5.770030,6.099229,6.233259,5.543495,5.767759,6.155905,6.111148,5.949481,6.342703,...,6.516922,6.113791,6.282113,6.248667,6.109480,6.043570,5.846802,6.429402,5.779815,6.241530
4,ACH-000509,5.480683,5.469742,6.509397,6.251005,5.190578,5.897085,6.148333,5.607481,5.871600,...,6.161981,6.777932,6.676390,6.695659,6.751029,6.385056,6.682612,6.757899,6.728570,6.879260
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
922,ACH-000655,5.977636,6.026483,6.480536,6.112056,5.878324,5.732508,5.981183,6.459139,5.642855,...,5.547818,5.703861,5.581725,5.506887,5.362247,5.322091,5.556126,5.544802,4.897559,5.506999
923,ACH-000273,5.957233,6.090834,5.323475,6.145795,5.741201,5.605435,6.184192,6.004195,5.663866,...,5.713210,5.651439,5.720680,5.387960,5.275798,5.289684,5.494241,5.533795,5.139488,5.452544
924,ACH-000504,5.967707,5.931487,5.620542,5.955261,5.935244,5.384674,5.955886,6.239657,5.527619,...,5.605403,5.317500,5.630315,5.433324,5.330957,5.481404,5.570553,5.146598,5.010639,5.114385
925,ACH-000825,5.962415,5.992640,6.296222,5.916386,6.043984,5.883976,5.954731,6.181054,5.820966,...,5.949798,6.249271,6.248746,6.130000,5.873297,5.826041,5.997694,6.411166,6.105394,6.387275
926,ACH-000084,6.332344,5.812531,5.446330,6.469052,5.501232,6.469954,6.136017,5.479015,5.694210,...,6.588558,6.548211,6.667652,6.868391,6.598519,5.956474,6.022471,6.862916,7.045115,6.841075

In [12]:
df_merged = pd.merge(IC50_AUC_SMILES, metabolomics, left_on='CellLineID', right_on='CellLineID', how='inner')

In [13]:
df_merged

,CellLineID,smiles,AUC,IC50,2-aminoadipate,3-phosphoglycerate,alpha-glycerophosphate,4-pyridoxate,aconitate,adenine,...,C56:8 TAG,C56:7 TAG,C56:6 TAG,C56:5 TAG,C56:4 TAG,C56:3 TAG,C56:2 TAG,C58:8 TAG,C58:7 TAG,C58:6 TAG
0,ACH-000001,CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=C4C3...,0.967187,NaN,6.067403,5.602360,5.556346,5.637666,6.040375,5.649284,...,5.945463,6.133054,6.177007,6.136944,5.899146,5.373586,5.608323,6.338148,6.264488,5.858530
1,ACH-000001,CCC1(CC2CC(C3=C(CCN(C2)C1)C4=CC=CC=C4N3)(C5=C(...,0.666062,NaN,6.067403,5.602360,5.556346,5.637666,6.040375,5.649284,...,5.945463,6.133054,6.177007,6.136944,5.899146,5.373586,5.608323,6.338148,6.264488,5.858530
2,ACH-000001,N.N.[Cl-].[Cl-].[Pt+2],0.977907,NaN,6.067403,5.602360,5.556346,5.637666,6.040375,5.649284,...,5.945463,6.133054,6.177007,6.136944,5.899146,5.373586,5.608323,6.338148,6.264488,5.858530
3,ACH-000001,CC1=C2C(C(=O)C3(C(CC4C(C3C(C(C2(C)C)(CC1OC(=O)...,0.922989,NaN,6.067403,5.602360,5.556346,5.637666,6.040375,5.649284,...,5.945463,6.133054,6.177007,6.136944,5.899146,5.373586,5.608323,6.338148,6.264488,5.858530
4,ACH-000001,COC1=C(C=C2C(=C1)N=CN=C2NC3=CC(=C(C=C3)F)Cl)OC...,0.957586,NaN,6.067403,5.602360,5.556346,5.637666,6.040375,5.649284,...,5.945463,6.133054,6.177007,6.136944,5.899146,5.373586,5.608323,6.338148,6.264488,5.858530
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66423,ACH-001307,CCC1=CC2CC(C3=C(CN(C2)C1)C4=CC=CC=C4N3)(C5=C(C...,0.836644,NaN,6.558230,5.647197,6.319460,6.153176,6.239952,5.836617,...,5.535541,6.008684,5.820675,5.555397,5.773193,5.782641,5.960382,5.650787,5.518399,5.701732
66424,ACH-001307,CC1=CN=C(N=C1C2=CNC(=C2)C(=O)NC(CO)C3=CC(=CC=C...,0.894145,NaN,6.558230,5.647197,6.319460,6.153176,6.239952,5.836617,...,5.535541,6.008684,5.820675,5.555397,5.773193,5.782641,5.960382,5.650787,5.518399,5.701732
66425,ACH-001307,CN1C(=C(C=N1)Cl)C2=C(OC(=C2)C(=O)NC(CC3=CC(=C(...,0.975099,NaN,6.558230,5.647197,6.319460,6.153176,6.239952,5.836617,...,5.535541,6.008684,5.820675,5.555397,5.773193,5.782641,5.960382,5.650787,5.518399,5.701732
66426,ACH-001307,CC1CN(CC(N1)C)C2=NC=C(C(=C2)C)C3=CC=C(C=C3)C4=...,0.892960,2.428133,6.558230,5.647197,6.319460,6.153176,6.239952,5.836617,...,5.535541,6.008684,5.820675,5.555397,5.773193,5.782641,5.960382,5.650787,5.518399,5.701732
66427,ACH-001307,C1CC(C1)NC2=NC=CC(=C2)C(=O)NCC(CN3CCC4=CC=CC=C...,0.912144,NaN,6.558230,5.647197,6.319460,6.153176,6.239952,5.836617,...,5.535541,6.008684,5.820675,5.555397,5.773193,5.782641,5.960382,5.650787,5.518399,5.701732

In [19]:
X = df_merged.drop(columns=["CellLineID", "AUC", "IC50"])
y = df_merged[["AUC", "IC50"]]
X.head()

,smiles,2-aminoadipate,3-phosphoglycerate,alpha-glycerophosphate,4-pyridoxate,aconitate,adenine,adipate,alpha-ketoglutarate,AMP,...,C56:8 TAG,C56:7 TAG,C56:6 TAG,C56:5 TAG,C56:4 TAG,C56:3 TAG,C56:2 TAG,C58:8 TAG,C58:7 TAG,C58:6 TAG
0,CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=C4C3...,6.067403,5.60236,5.556346,5.637666,6.040375,5.649284,6.18445,5.85209,5.597239,...,5.945463,6.133054,6.177007,6.136944,5.899146,5.373586,5.608323,6.338148,6.264488,5.85853
1,CCC1(CC2CC(C3=C(CCN(C2)C1)C4=CC=CC=C4N3)(C5=C(...,6.067403,5.60236,5.556346,5.637666,6.040375,5.649284,6.18445,5.85209,5.597239,...,5.945463,6.133054,6.177007,6.136944,5.899146,5.373586,5.608323,6.338148,6.264488,5.85853
2,N.N.[Cl-].[Cl-].[Pt+2],6.067403,5.60236,5.556346,5.637666,6.040375,5.649284,6.18445,5.85209,5.597239,...,5.945463,6.133054,6.177007,6.136944,5.899146,5.373586,5.608323,6.338148,6.264488,5.85853
3,CC1=C2C(C(=O)C3(C(CC4C(C3C(C(C2(C)C)(CC1OC(=O)...,6.067403,5.60236,5.556346,5.637666,6.040375,5.649284,6.18445,5.85209,5.597239,...,5.945463,6.133054,6.177007,6.136944,5.899146,5.373586,5.608323,6.338148,6.264488,5.85853
4,COC1=C(C=C2C(=C1)N=CN=C2NC3=CC(=C(C=C3)F)Cl)OC...,6.067403,5.60236,5.556346,5.637666,6.040375,5.649284,6.18445,5.85209,5.597239,...,5.945463,6.133054,6.177007,6.136944,5.899146,5.373586,5.608323,6.338148,6.264488,5.85853

In [20]:
y.head()

        AUC  IC50
0  0.967187   NaN
1  0.666062   NaN
2  0.977907   NaN
3  0.922989   NaN
4  0.957586   NaN

In [22]:
from sklearn.model_selection import train_test_split

# Train-Test Split (80% train, 20% test)
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.1, random_state=42)

print(f"Train X: {train_X.shape}, Train y: {train_y.shape}")
print(f"Test X: {test_X.shape}, Test y: {test_y.shape}")

Train X: (59785, 226), Train y: (59785, 2)
Test X: (6643, 226), Test y: (6643, 2)

# Model Design

In [ ]:
import torch
import torch.nn as nn
import math

# PositionalEncoding
class PositionalEncoding(nn.Module):
    def __init__(self, d_model, max_len=5000):
        super(PositionalEncoding, self).__init__()
        pe = torch.zeros(max_len, d_model)
        position = torch.arange(0, max_len, dtype=torch.float).unsqueeze(1)
        div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model))
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        self.pe = pe.unsqueeze(1)  # (max_len, 1, d_model)
    
    def forward(self, x):
        # x: (seq_len, batch_size, d_model)
        return x + self.pe[:x.size(0)]

# MultiTaskDrugRegressor: IC50, AUC regression (separately)
class MultiTaskDrugRegressor(nn.Module):
    def __init__(self, vocab_size, d_model, nhead, num_layers, num_omics):
        super(MultiTaskDrugRegressor, self).__init__()
        # SMILES 처리 (Transformer 기반)
        self.embedding = nn.Embedding(vocab_size, d_model, padding_idx=0)
        self.positional_encoding = PositionalEncoding(d_model)
        encoder_layer = nn.TransformerEncoderLayer(d_model, nhead)
        self.transformer_encoder = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)
        
        # Omics 데이터 처리
        self.omics_fc = nn.Linear(num_omics, d_model)
        
        # 결합된 표현은 2*d_model 차원
        # 각각의 회귀 헤드: IC50과 AUC 예측 (출력은 단일값)
        self.ic50_head = nn.Linear(2*d_model, 1)
        self.auc_head = nn.Linear(2*d_model, 1)
        
    def forward(self, smiles_tokens, omics_data):
        """
        smiles_tokens: (batch_size, seq_len)  -- 정수 인덱스로 구성 (패딩 토큰은 0)
        omics_data: (batch_size, num_omics)
        """
        # SMILES 처리: 패딩 마스크 생성
        src_key_padding_mask = (smiles_tokens == 0)  # (batch_size, seq_len)
        embedded = self.embedding(smiles_tokens).transpose(0, 1)  # (seq_len, batch_size, d_model)
        encoded = self.positional_encoding(embedded)
        # Transformer 인코더 (패딩 무시)
        encoded = self.transformer_encoder(encoded, src_key_padding_mask=src_key_padding_mask)
        
        # 평균 풀링: 패딩을 제외하고 각 배치에 대해 평균값 산출
        # encoded: (seq_len, batch_size, d_model)
        # 먼저, 패딩 위치를 0으로 채우고
        encoded = encoded.masked_fill(src_key_padding_mask.transpose(0,1).unsqueeze(-1), 0)
        sum_encoded = encoded.sum(dim=0)  # (batch_size, d_model)
        lengths = (~src_key_padding_mask).sum(dim=1, keepdim=True)  # (batch_size, 1)
        smiles_repr = sum_encoded / lengths.clamp(min=1)
        
        # Omics 데이터 처리
        omics_repr = self.omics_fc(omics_data)  # (batch_size, d_model)
        
        # 융합: SMILES 표현과 omics 표현을 concatenate
        fused = torch.cat([smiles_repr, omics_repr], dim=1)  # (batch_size, 2*d_model)
        
        # 두 개의 회귀 헤드로 예측
        ic50_pred = self.ic50_head(fused)  # (batch_size, 1)
        auc_pred = self.auc_head(fused)    # (batch_size, 1)
        
        return ic50_pred, auc_pred

In [ ]:


######################################
# 예제: Combined Dataset & Training Step
######################################
# 예시: 각 샘플은 omics, SMILES, 그리고 두 타겟 중 하나만 실제값을 가짐.
# NaN으로 표시된 타겟은 손실 계산 시 무시.
# dataset_sample: (smiles_tokens, omics_data, ic50_target, auc_target)
# 예를 들어, IC50 데이터셋의 경우 auc_target은 NaN, AUC 데이터셋의 경우 ic50_target은 NaN

# 샘플 배치 데이터 (batch_size=4, seq_len=10, num_omics=5)
# 임의로 생성한 정수 시퀀스 (패딩 토큰은 0)
smiles_tokens = torch.randint(1, 100, (4, 10))
# 예시로, 첫 두 샘플은 IC50 데이터셋, 나머지 두 샘플은 AUC 데이터셋으로 가정
# (IC50 데이터: ic50_target은 실제 값, auc_target은 NaN)
# (AUC 데이터: auc_target은 실제 값, ic50_target은 NaN)
omics_data = torch.randn(4, 5)
ic50_targets = torch.tensor([1.2, 0.8, float('nan'), float('nan')]).unsqueeze(1)
auc_targets  = torch.tensor([float('nan'), float('nan'), 0.45, 0.60]).unsqueeze(1)

# 모델 생성
model = MultiTaskDrugRegressor(vocab_size=100, d_model=128, nhead=4, num_layers=2, num_omics=5)

# Forward pass
ic50_pred, auc_pred = model(smiles_tokens, omics_data)

print("IC50 Predictions:", ic50_pred)
print("AUC Predictions:", auc_pred)

######################################
# 예제: 손실 계산 (유효한 타겟에 대해서만)
######################################
criterion = nn.MSELoss()

# 마스크를 통해 유효한 샘플만 선택 (NaN 체크)
ic50_mask = ~torch.isnan(ic50_targets)
auc_mask  = ~torch.isnan(auc_targets)

loss = 0.0
if ic50_mask.sum() > 0:
    loss_ic50 = criterion(ic50_pred[ic50_mask], ic50_targets[ic50_mask])
    loss += loss_ic50
if auc_mask.sum() > 0:
    loss_auc = criterion(auc_pred[auc_mask], auc_targets[auc_mask])
    loss += loss_auc

print("Total Loss:", loss.item())